/* eslint-disable import/extensions */

'use client';

// import { Inter } from 'next/font/google';
import { Provider } from 'react-redux';
import { store } from '../redux/store';
import './global.scss';
import Footer from './components/Footer/Footer';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <Provider store={store}>{children}</Provider>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
