import './global.scss';
import Footer from './components/Footer/Footer';
import ReduxProvider from './components/Provider/Provider';

export const metadata = {
  title: 'Year Manga Anime Wrapped',
  // description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <ReduxProvider>
        {children}
      </ReduxProvider>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
